class width_item;
  logic [7:0] value;
  logic signed [7:0] signed_value;
  logic [31:0] packed_value;
endclass
module sv_compound_operation_width;
  logic [7:0] value, da[], queue_value[$];
  logic signed [7:0] signed_value;
  logic [63:0] wide;
  logic [31:0] operand;
  width_item h;
  int offset, calls;
  function automatic int index_once();
    calls++;
    return 0;
  endfunction
  initial begin
    value = 128;
    value /= 32'd256;
    if (value !== 0) $fatal(1, "wide literal divisor");
    operand = 256;
    value = 128;
    value %= operand;
    if (value !== 128) $fatal(1, "wide runtime remainder");
    value = 128;
    value >>= 32'd256;
    if (value !== 0) $fatal(1, "wide literal shift");
    value = 128;
    value <<= operand;
    if (value !== 0) $fatal(1, "wide runtime shift");
    value = 128;
    value >>= '1;
    if (value !== 64) $fatal(1, "self-determined unbased shift");
    signed_value = -128;
    signed_value /= 32'sd2;
    if (signed_value !== -8'sd64) $fatal(1, "signed operand extension");
    signed_value = -128;
    signed_value /= 32'd256;
    if (signed_value !== 0) $fatal(1, "mixed operand extension");
    signed_value = -128;
    signed_value >>>= 32'd256;
    if (signed_value !== -8'sd1) $fatal(1, "wide arithmetic shift");
    wide = 0;
    wide += (8'd255 + 8'd1);
    if (wide !== 256) $fatal(1, "RHS context widening");
    value = 255;
    value += 16'd2;
    if (value !== 1) $fatal(1, "final truncation");
    value = 128;
    {value} /= 32'd256;
    if (value !== 0) $fatal(1, "concatenation width");
    h = new;
    h.value = 128;
    h.value /= operand;
    if (h.value !== 0) $fatal(1, "property divisor");
    h.signed_value = -128;
    h.signed_value /= 32'sd2;
    if (h.signed_value !== -8'sd64) $fatal(1, "signed property extension");
    h.packed_value = 32'haa800055;
    h.packed_value[23:16] /= 32'd256;
    if (h.packed_value !== 32'haa000055) $fatal(1, "constant part preservation");
    h.packed_value = 32'haa800055;
    offset = 16;
    h.packed_value[offset +: 8] >>= operand;
    if (h.packed_value !== 32'haa000055) $fatal(1, "variable part preservation");
    da = new[1];
    da[0] = 128;
    da[index_once()] /= operand;
    if (da[0] !== 0 || calls != 1) $fatal(1, "array operation/index");
    queue_value.push_back(128);
    queue_value[0] >>= operand;
    if (queue_value[0] !== 0) $fatal(1, "queue shift");
    $display("PASSED");
  end
endmodule
